export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS'
export const ADD_ITEM_TO_ORDER = 'ADD_TO_ORDER'
export const REMOVE_ITEM_FROM_ORDER = 'REMOVE_ITEM_FROM_ORDER'
export const SUBMIT_ORDER = 'SUBMIT_ORDER'